/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ical;

import java.util.ArrayList;
import java.util.Scanner;


public class App {
 public static void main(String[] args) throws InterruptedException {  
    App chamarMenu = new App(); 
        chamarMenu.menu();
}     

       private ArrayList<VCalendar>iCalendar=new ArrayList<>();        
       
            void menu() throws InterruptedException{
            Scanner entrada = new Scanner(System.in);         
            while(true){
                Thread.sleep(300);
                System.out.println("Entre com a opção desejada:");
                System.out.println("1 - Cadastro de evento");
                System.out.println("2 - Consulta de eventos cadastrados"); 
                System.out.println("3 - Remover um evento"); 
                System.out.println("4 - Alterar um evento");
                           
                int linha = entrada.nextInt();                                                  
            
                switch(linha){                       

                    case 1:
                        String s =entrada.nextLine();
                        System.out.println("Informe o nome da empresa");    
                        String empresa =entrada.nextLine();
                        System.out.println("Informe o nome do App");    
                        String app =entrada.nextLine();
                        System.out.println("Informe o idioma");    
                        String idioma =entrada.nextLine();
                        System.out.println("Dia de inicio");            
                        int diaI = entrada.nextInt();
                        System.out.println("Mes de inicio");
                        int mesI = entrada.nextInt();
                        System.out.println("Ano de inicio"); 
                        int anoI = entrada.nextInt();
                        System.out.println("Hora de inicio");
                        int hrI = entrada.nextInt();
                        System.out.println("Minuto de inicio"); 
                        int mmI = entrada.nextInt();
                        System.out.println("Segundo de inicio"); 
                        int ssI = entrada.nextInt();
                        System.out.println("Dia final");
                        int diaF = entrada.nextInt();
                        System.out.println("Mes final");
                        int mesF = entrada.nextInt();
                        System.out.println("Ano final");
                        int anoF = entrada.nextInt();
                        System.out.println("Hora final");
                        int hrF = entrada.nextInt();
                        System.out.println("Minuto final");
                        int mmF = entrada.nextInt(); 
                        System.out.println("Segundo final");
                        int ssF = entrada.nextInt();                               
                        String ss =entrada.nextLine();  
                        System.out.println("Sumário da agenda"); 
                        String sumario = entrada.nextLine();
                        
                        for(VCalendar elemento: iCalendar){
                            if(elemento.getSummary().equals(sumario)){
                            System.out.println("sumário ja cadastrado");
                            System.out.println("informe novo sumário");
                            sumario=entrada.nextLine();                                                  

                            }
                        }      
                       
                        System.out.println("Local do evento"); 
                        String local = entrada.nextLine(); 
                        System.out.println("É um evento com recorrência?");
                        System.out.println("1-sim\n2-não");
                        String recorrencia = entrada.nextLine(); 
                        if(recorrencia.equals("2")){
                            try {
                                iCalendar.add(new VCalendar(empresa,app,idioma,anoI, mesI, diaI, hrI, mmI,ssI, anoF, mesF, diaF, hrF, mmF, ssF,sumario, local));
                                System.out.println("Evento cadastrado com sucesso");  
                            }
                           catch(Exception e){
                                   break;
                            }                 
                            break;      
                        }else{
                            System.out.println("Qual a frequencia:\n1-diario\n2-semanal\n3-mensal\n4-anual"); 
                            int freq = entrada.nextInt();
                            String frequencia=null;;
                            switch(freq){
                                case 1:
                                    frequencia="diario";
                                    break;
                                case 2:
                                    frequencia="semanal";
                                    break;
                                case 3:
                                frequencia="mensal";
                                    break;
                                case 4:
                                    frequencia="anual";
                                    break;
                                default:
                                    System.out.println("Opção inválida\n");                              
                                     break; 
                            }
                        

                            System.out.println("Qual intervalo de repetição ?");
                            int intervalo = entrada.nextInt();
                            System.out.println("Qual o dia final da repetição ?");
                            int diaFrep = entrada.nextInt();
                            System.out.println("Qual o mes final da repetição ?");
                            int mesFrep = entrada.nextInt();
                            System.out.println("Qual o ano final da repetição ?");
                            int anoFrep = entrada.nextInt();
                            System.out.println("Qual a hora final da repetição ?");
                            int hrFrep = entrada.nextInt();
                            System.out.println("Qual o minuto final da repetição ?");
                            int mmFrep = entrada.nextInt();
                            System.out.println("Qual o segundo final da repetição ?");
                            int ssFrep = entrada.nextInt();
                            String sss =entrada.nextLine();
                            System.out.println("Qual dia da  semana ocorre repetição ?");                            
                            System.out.println("1-segunda\n2-terça\n3-quarta\n4-quinta\n5-sexta\n6-sabado\n7-domingo");  
                            int dia = entrada.nextInt(); 
                            String byday=null;
                            switch(dia){
                            case 1:
                                    byday="segunda";
                                    break;
                            case 2:
                                    byday="terca";  
                                    break;
                            case 3:
                                    byday="quarta";
                                    break;
                            case 4:
                                    byday="quinta";
                                    break;
                            case 5:
                                    byday="sexta";
                                    break;
                            case 6:
                                    byday="sabado";
                                    break;
                            case 7:
                                    byday="domingo";
                                    break;
                            default:
                                    System.out.println("Opção inválida");                              
                                    break;            
                            
                            }
                        
                        System.out.println("Existe data a ser excluída de eventos recorrentes ?"); 
                        System.out.println("1-sim\n2-não");
                        int opt = entrada.nextInt(); 
                        
                        switch(opt){

                            case 1:
                                    System.out.println("Dia de inicio");            
                                    int diaEx = entrada.nextInt();
                                    System.out.println("Mes de inicio");
                                    int mesEx = entrada.nextInt();
                                    System.out.println("Ano de inicio"); 
                                    int anoEx = entrada.nextInt();
                                    try {
                                         iCalendar.add(new VCalendar(empresa,app,idioma,anoI, mesI, diaI, hrI, mmI,ssI, anoF, mesF, diaF, hrF, mmF,ssF, sumario, 
                                         local,frequencia,intervalo,anoFrep,mesFrep,diaFrep,hrFrep,mmFrep,ssFrep,byday,anoEx,mesEx,diaEx));
                                         System.out.println("Evento cadastrado com sucesso");  
                               }
                                        catch(Exception e){

                                   break;
                               }           
                  
                                 break;
                            case 2:
                                    try {
                                        iCalendar.add(new VCalendar(empresa,app,idioma,anoI, mesI, diaI, hrI, mmI,ssI, anoF, mesF, diaF, hrF, mmF,ssF, sumario, 
                                        local,frequencia,intervalo,anoFrep,mesFrep,diaFrep,hrFrep,mmFrep,ssFrep,byday));
                                        System.out.println("Evento cadastrado com sucesso");  
                                       }
                                   catch(Exception e){
                                           break;
                                       }           
                          
                                    break; 
                        }
                        break;

                    }                           
                        

                    case 2:
                            if(iCalendar.size()>0){
                                System.out.println("BEGIN:VCALENDAR");
                                 for(VCalendar elemento: iCalendar){
                                    System.out.println(elemento);
                                    }
                                System.out.println("END:VCALENDAR");
                            }else{  
                                 System.out.println("Sem eventos na agenda");                            
                                }   
                       
                        break;                          

                    case 3:
                    if(iCalendar.size()>0){
                        System.out.println("Qual evento deseja remover ?");                                    
                        entrada.nextLine(); 
                        String remover = entrada.nextLine();
                    
                         if(iCalendar.removeIf(elemento->elemento.getSummary().equals(remover))){
                                System.out.println("Evento removido");
                        }else{
                                System.out.println("Evento não localizado");
                        }
                    }else{  
                        System.out.println("Sem eventos na agenda");                            
                    }   
                            break;
            
                    case 4:
                        if(iCalendar.size()>0){
                            System.out.println("O que deseja alterar ?");
                            System.out.println("1-Data inicial\n2-Data Final\n3-Sumário\n4-Local\n5-Exdate");
                            int opt = entrada.nextInt(); 
                       
                        
                        switch(opt){

                            case 1:
                            //percorre a lista pelo sumario e altera dtstart
                                entrada.nextLine();
                                System.out.println("Qual sumário ?");
                                String sum1 =entrada.nextLine();
                                try {
                                    iCalendar.forEach(elemento->{
                                        if (elemento.getSummary().equals(sum1)){     
                                                System.out.println("Qual dia ?");
                                                int dia = entrada.nextInt();
                                                System.out.println("Qual mes ?");
                                                int mes = entrada.nextInt();
                                                System.out.println("Qual ano ?");
                                                int ano = entrada.nextInt();
                                                System.out.println("Qual hora ?");
                                                int hora = entrada.nextInt();
                                                System.out.println("Qual minuto ?");
                                                int minuto = entrada.nextInt();
                                                System.out.println("Qual segundo ?");
                                                int segundo = entrada.nextInt();
                                                elemento.setDtstart(ano, mes, dia, hora, minuto, segundo);; 
                                                System.out.println("Evento atualizado");                                                                            
                                          
                                        }});
                                    
                                } catch (Exception e) {
                                    System.out.println("evento não localizado");
                                }break;
                                
                                    
                            case 2:
                            //percorre a lista pelo sumario e altera dtend
                                entrada.nextLine();
                                System.out.println("Qual sumário ?");
                                String sum =entrada.nextLine();
                                iCalendar.forEach(elemento->{
                                    if (elemento.getSummary().equals(sum)){                                         
                                        System.out.println("Qual dia ?");
                                        int dia = entrada.nextInt();
                                        System.out.println("Qual mes ?");
                                        int mes = entrada.nextInt();
                                        System.out.println("Qual ano ?");
                                        int ano = entrada.nextInt();
                                        System.out.println("Qual hora ?");
                                        int hora = entrada.nextInt();
                                        System.out.println("Qual minuto ?");
                                        int minuto = entrada.nextInt();
                                        System.out.println("Qual segundo ?");
                                        int segundo = entrada.nextInt();
                                        elemento.setDtend(ano, mes, dia, hora, minuto, segundo);;
                                        System.out.println("Evento atualizado");
                                                
                                    }});break;

                            case 3:
                            //percorre a lista pelo sumario e altera o sumario
                                System.out.println("Qual sumário ?");
                                entrada.nextLine();
                                String sum2 =entrada.nextLine();
                                iCalendar.forEach(elemento->{                                    
                                    if (elemento.getSummary().equals(sum2)){ 
                                        System.out.println("Qual novo sumário ?");
                                        String nova =entrada.nextLine();
                                        if(elemento.getSummary().equals(nova)){
                                            System.out.println("sumário ja existe");
                                            System.out.println("Qual novo sumário ?");
                                            nova =entrada.nextLine(); 
                                            elemento.setSummary(nova);             

                                        }  
                                        
                                       else{
                                        elemento.setSummary(nova);
                                        System.out.println("Evento atualizado");}
                                    
                                }
                            });break;   
                            
                            case 4:
                            //percorre a lista pelo sumario e altera o local
                                System.out.println("Qual sumário ?");
                                entrada.nextLine();
                                sum =entrada.nextLine();
                                iCalendar.forEach(elemento->{                                    
                                    if (elemento.getSummary().equals(sum)){ 
                                        System.out.println("Qual novo local?");
                                        String nova =entrada.nextLine();          
                                        elemento.setLocation(nova);
                                        System.out.println("Evento atualizado");
                                    
                                }});break; 
                            
                            case 5:
                             //percorre a lista pelo sumario e altera o exdate
                             System.out.println("Qual sumário ?");
                             entrada.nextLine();
                             sum =entrada.nextLine();
                             iCalendar.forEach(elemento->{                                    
                                 if (elemento.getSummary().equals(sum)){ 
                                    System.out.println("Qual dia ?");
                                    int dia = entrada.nextInt();
                                    System.out.println("Qual mes ?");
                                    int mes = entrada.nextInt();
                                    System.out.println("Qual ano ?");
                                    int ano = entrada.nextInt();
                                    elemento.setExdate(ano, mes, dia);
                                    System.out.println("Evento atualizado");
                                 
                             }else{
                                 System.out.println("Evento não localizado"); 
                             }});break;                            
                            
                            default:                                   
                            
                                break;                       
                            }                           
                            
                        }else{
                            System.out.println("Sem eventos na agenda");
                        }
                    
                    
                    default:                            
                            break;                   

                }
            }    
        }  
    } 



